/**
 *
 * @author ferma
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interface = new javax.swing.JPanel();
        textName = new java.awt.Label();
        btnABB = new javax.swing.JButton();
        btnAVL = new javax.swing.JButton();
        btnAVP = new javax.swing.JButton();
        textTitle = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto ESDD Árvores");
        setBackground(new java.awt.Color(31, 29, 46));
        setName("jFrameMenu"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        Interface.setBackground(new java.awt.Color(31, 29, 46));
        Interface.setPreferredSize(new java.awt.Dimension(400, 400));

        textName.setAlignment(java.awt.Label.CENTER);
        textName.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textName.setForeground(new java.awt.Color(235, 111, 146));
        textName.setName(""); // NOI18N
        textName.setText("2° Projeto ESDD por Aloísio, Fernanda e Guilherme");

        btnABB.setBackground(new java.awt.Color(235, 190, 186));
        btnABB.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        btnABB.setForeground(new java.awt.Color(235, 111, 146));
        btnABB.setText("ABB");
        btnABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABBActionPerformed(evt);
            }
        });

        btnAVL.setBackground(new java.awt.Color(235, 190, 186));
        btnAVL.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        btnAVL.setForeground(new java.awt.Color(235, 111, 146));
        btnAVL.setText("AVL");
        btnAVL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAVLActionPerformed(evt);
            }
        });

        btnAVP.setBackground(new java.awt.Color(235, 190, 186));
        btnAVP.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        btnAVP.setForeground(new java.awt.Color(235, 111, 146));
        btnAVP.setText("AVP");
        btnAVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAVPActionPerformed(evt);
            }
        });

        textTitle.setAlignment(java.awt.Label.CENTER);
        textTitle.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        textTitle.setForeground(new java.awt.Color(235, 111, 146));
        textTitle.setText("Árvores");

        javax.swing.GroupLayout InterfaceLayout = new javax.swing.GroupLayout(Interface);
        Interface.setLayout(InterfaceLayout);
        InterfaceLayout.setHorizontalGroup(
            InterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfaceLayout.createSequentialGroup()
                .addGroup(InterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfaceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InterfaceLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(InterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnABB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAVL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAVP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(InterfaceLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InterfaceLayout.setVerticalGroup(
            InterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnABB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAVL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAVP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Interface, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Interface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABBActionPerformed
        new SimuladorABB();
    }//GEN-LAST:event_btnABBActionPerformed

    private void btnAVLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAVLActionPerformed
        new SimuladorAVL();
    }//GEN-LAST:event_btnAVLActionPerformed

    private void btnAVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAVPActionPerformed
        new SimuladorAVP();
    }//GEN-LAST:event_btnAVPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Interface;
    private javax.swing.JButton btnABB;
    private javax.swing.JButton btnAVL;
    private javax.swing.JButton btnAVP;
    private java.awt.Label textName;
    private java.awt.Label textTitle;
    // End of variables declaration//GEN-END:variables
}
